version: '3.8'

services:
  vllm-qwen3-30b-a3b-instruct-2507:
    image: vllm/vllm-openai:v0.10.1
    container_name: vllm-qwen3-30b-a3b-instruct-2507
    networks:
      - shared-vllm-network
    ports:
      - "9999:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: >
      --model Qwen/Qwen3-30B-A3B-Instruct-2507
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size 1
      --gpu-memory-utilization 0.95
      --max-model-len 262144
      --trust-remote-code
      --enable-auto-tool-choice
      --tool-call-parser hermes
    restart: unless-stopped

networks:
  shared-vllm-network:
    external: true